spring:
  application:
    name: ddb-practice
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: fakeMyKeyId
        secret-key: fakeSecretAccessKey
      dynamodb:
        endpoint: http://localhost:8000
        region: us-east-1

server:
  port: 8080

logging:
  level:
    com.example.ddbpractice: DEBUG
    software.amazon.awssdk: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info 